[project]
name = "personal-project"
version = "0.1.0"
description = "A CLI password strength checker"
readme = "README.md"
authors = [
    { name = "benjbread", email = "benjbreadon@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
pwcheck = "pwcheck.main:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pwcheck"
